
CREATE TABLE PTC_AUDITORIA_CAMPO_DESC_ACD ( 
    ACD_ID             	INTEGER NOT NULL,
    ACD_PRO_ID         	INTEGER NOT NULL,
    ACD_CAMPO          	VARCHAR(100) NOT NULL,
    ADT_DESCRICAO_CAMPO	VARCHAR(250) NOT NULL,
    PRIMARY KEY(ACD_ID)
    )
GO

CREATE TABLE PTC_CIDADE_CID ( 
    CID_ID    	INTEGER NOT NULL,
    CID_CODIGO	VARCHAR(10) NOT NULL,
    CID_NOME  	VARCHAR(50) NOT NULL,
    CID_EST_ID	INTEGER NOT NULL,
    PRIMARY KEY(CID_ID)
)

CREATE TABLE PTC_ENTIDADE_ENT ( 
    ENT_ID             	INTEGER NOT NULL,
    ENT_CRIADOR_ID     	INTEGER DEFAULT 0 NULL,
    ENT_PROPRIETARIO_ID	INTEGER DEFAULT 0 NULL,
    ENT_MODIFICADO_POR 	INTEGER DEFAULT 0 NULL,
    ENT_DESCRICAO      	VARCHAR(100) NULL,
    ENT_OBSERVACAO     	VARCHAR(255) DEFAULT '' NULL,
    ENT_CREATEDTIME    	VARCHAR(25) NOT NULL,
    ENT_MODIFIEDTIME   	VARCHAR(25) NOT NULL,
    ENT_VIEWEDTIME     	VARCHAR(25) DEFAULT NULL NULL,
    ENT_STATUS         	VARCHAR(50) DEFAULT NULL NULL,
    ENT_VERSAO         	INTEGER DEFAULT 0 NULL,
    ENT_LIXEIRA        	INTEGER DEFAULT 0 NULL,
    ENT_BLOQUEADO      	INTEGER DEFAULT 0 NULL,
    ENT_REPRESENTANTE  	INTEGER DEFAULT NULL NULL,
    PRIMARY KEY(ENT_ID)
)
GO
CREATE TABLE PTC_ESTADO_EST ( 
    EST_ID       	INTEGER NOT NULL,
    EST_SIGLA    	CHAR(2) NOT NULL,
    EST_NOME     	VARCHAR(50) NOT NULL,
    EST_CODIGO_UF	VARCHAR(20) NOT NULL,
    EST_PAI_ID   	INTEGER NOT NULL,
    EST_REGIAO   	VARCHAR(100) DEFAULT NULL NULL,
    PRIMARY KEY(EST_ID)
)
GO
CREATE TABLE PTC_MENU_MEN ( 
    MEN_ID             	INTEGER NOT NULL,
    MEN_PRO_ID         	INTEGER DEFAULT NULL NULL,
    MEN_PRINCIPAL      	INTEGER DEFAULT 0 NOT NULL,
    MEN_DESCRICAO_CURTA	VARCHAR(20) DEFAULT NULL NULL,
    MEN_DESTINO        	VARCHAR(200) NULL,
    MEN_ID_OWNER       	INTEGER DEFAULT NULL NULL,
    MEN_ORDEM          	INTEGER DEFAULT NULL NULL,
    PRIMARY KEY(MEN_ID)
)
GO
CREATE TABLE PTC_MODULO_EMPRESA_MEP ( 
    MEP_ID    	INTEGER NOT NULL,
    MEP_EMP_ID	INTEGER NOT NULL,
    MEP_MOD_ID	INTEGER NOT NULL,
    PRIMARY KEY(MEP_ID)
)
GO
CREATE TABLE PTC_MODULO_MOD ( 
    MOD_ID             	INTEGER NOT NULL,
    MOD_NOME           	VARCHAR(30) NOT NULL,
    MOD_DESCRICAO_CURTA	VARCHAR(50) NOT NULL,
    MOD_DESCRICAO      	VARCHAR(250) NULL,
    PRIMARY KEY(MOD_ID)
)
GO
CREATE TABLE PTC_NOTIFICACAO_NOT ( 
    NOT_ID         	SERIAL,
    NOT_TITULO     	VARCHAR(250) NULL,
    NOT_DESCRICAO  	VARCHAR(250) NULL,
    NOT_PROGRAMA   	VARCHAR(20) NULL,
    NOT_VIZUALIZADO	INTEGER NULL,
    NOT_VALOR      	VARCHAR(50) NULL,
    NOT_USU_ID     	INTEGER NULL,
    NOT_EXPIRACAO  	DATETIME YEAR TO MINUTE,
    PRIMARY KEY(NOT_ID)
)
GO

CREATE TABLE PTC_PADROES_MODULO_PROG_PMP ( 
    PMP_ID        	INTEGER NOT NULL,
    PMP_TIPO      	CHAR(1) DEFAULT NULL NULL,
    PMP_PRO_MOD_ID	INTEGER DEFAULT NULL NULL,
    PMP_PARAMETRO 	VARCHAR(100) DEFAULT NULL NULL,
    PMP_VALOR     	VARCHAR(250) DEFAULT NULL NULL,
    PMP_TIPO_CAMPO	VARCHAR(20) DEFAULT NULL NULL,
    PMP_DESCRICAO 	VARCHAR(255) DEFAULT '' NULL,
    PRIMARY KEY(PMP_ID)
)
GO
CREATE TABLE PTC_PAIS_PAI ( 
    PAI_ID        	INTEGER NOT NULL,
    PAI_DESCRICAO 	VARCHAR(50) NOT NULL,
    PAI_CODIGO    	VARCHAR(5) NOT NULL,
    PAI_CONTINENTE	VARCHAR(50) DEFAULT NULL NULL,
    PAI_MERCADO   	VARCHAR(50) DEFAULT NULL NULL,
    PRIMARY KEY(PAI_ID)
)
GO
CREATE TABLE PTC_PERFIL_PER ( 
    PER_ID               	INTEGER NOT NULL,
    PER_NOME             	VARCHAR(40) NOT NULL,
    PER_APROVA_FINANCEIRO	INTEGER DEFAULT 0 NULL,
    PER_APROVA_COMERCIAL 	INTEGER DEFAULT 0 NULL,
    PRIMARY KEY(PER_ID)
)
GO
CREATE TABLE PTC_PERFIL_PROGRAMA_PEP ( 
    PEP_ID     	INTEGER NOT NULL,
    PEP_PER_ID 	INTEGER NOT NULL,
    PEP_PRO_ID 	INTEGER NOT NULL,
    PEP_ACESSAR	INTEGER DEFAULT 0 NOT NULL,
    PEP_INCLUIR	INTEGER DEFAULT 0 NOT NULL,
    PEP_ALTERAR	INTEGER DEFAULT 0 NOT NULL,
    PEP_LIXEIRA	INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY(PEP_ID)
)
GO
CREATE TABLE PTC_PERFIL_USUARIO_PFU ( 
    PFU_ID    	INTEGER NOT NULL,
    PFU_PER_ID	INTEGER NOT NULL,
    PFU_USU_ID	INTEGER NOT NULL,
    PRIMARY KEY(PFU_ID)
)
GO
CREATE TABLE PTC_PESSOA_PES ( 
    PES_ID                        	INTEGER NOT NULL,
    PES_TIPO                      	INTEGER DEFAULT NULL NULL,
    PES_CPF                       	CHAR(14) DEFAULT NULL NULL,
    PES_CNPJ                      	VARCHAR(20) DEFAULT NULL NULL,
    PES_NOME_REDUZIDO             	VARCHAR(15) DEFAULT NULL NULL,
    PES_INSCRICAO_ESTADUAL        	VARCHAR(16) DEFAULT NULL NULL,
    PES_INSCRICAO_MUNICIPAL       	VARCHAR(16) DEFAULT NULL NULL,
    PES_RAZAO_SOCIAL              	VARCHAR(60) DEFAULT NULL NULL,
    PES_SUFRAMA                   	VARCHAR(60) DEFAULT NULL NULL,
    PES_LOGRADOURO                	VARCHAR(60) DEFAULT NULL NULL,
    PES_NUMERO                    	VARCHAR(15) DEFAULT NULL NULL,
    PES_BAIRRO                    	VARCHAR(30) DEFAULT NULL NULL,
    PES_CID_ID                    	INTEGER DEFAULT NULL NULL,
    PES_CEP                       	CHAR(8) DEFAULT NULL NULL,
    PES_TELEFONE                  	VARCHAR(25) NULL,
    PES_CELULAR                   	VARCHAR(25) NULL,
    PES_DATA_VALIDADE_SUFRAMA     	VARCHAR(20) DEFAULT NULL NULL,
    PES_DATA_NASC_FUND            	VARCHAR(20) DEFAULT NULL NULL,
    PES_FORNECEDOR                	VARCHAR(20) DEFAULT NULL NULL,
    PES_COD                       	VARCHAR(20) DEFAULT NULL NULL,
    PES_CLIENTE                   	VARCHAR(20) DEFAULT NULL NULL,
    PES_FUNCIONARIO               	VARCHAR(20) DEFAULT NULL NULL,
    PES_OBSERVACAO                	VARCHAR(250) NULL,
    PES_ORGAO_EMISSOR             	VARCHAR(20) DEFAULT NULL NULL,
    PES_RG                        	VARCHAR(20) DEFAULT NULL NULL,
    PES_TELEFONE_FAX              	VARCHAR(25) NULL,
    PES_TRANSPORTADORA            	VARCHAR(20) DEFAULT NULL NULL,
    PES_VENDEDOR                  	VARCHAR(20) DEFAULT NULL NULL,
    PES_EMAIL                     	VARCHAR(100) DEFAULT NULL NULL,
    PES_EMAIL_SECUNDARIO          	VARCHAR(100) DEFAULT NULL NULL,
    PES_EMAIL_NFE                 	VARCHAR(100) DEFAULT NULL NULL,
    PES_SITUACAO                  	CHAR(1) DEFAULT NULL NULL,
    PES_IMAGEM                    	VARCHAR(250) NULL,
    PES_TIPO_CADASTRO             	CHAR(1) DEFAULT NULL NULL,
    PES_ISENTO                    	CHAR(1) DEFAULT NULL NULL,
    PES_SIMPLES_NACIONAL          	CHAR(1) DEFAULT NULL NULL,
    PES_STATUS                    	CHAR(2) DEFAULT NULL NULL,
    PES_RECEBE_INFO_NITEM_PED_XPED	INTEGER DEFAULT 0 NULL,
    PES_QTD_MAX_DIAS_CONDICAO_PGTO	INTEGER DEFAULT NULL NULL,
    PES_MOTIVO_REPROVACAO         	VARCHAR(250) NULL,
    PES_PORTADOR                  	VARCHAR(20) DEFAULT NULL NULL,
    PES_LTP_ID                    	INTEGER DEFAULT NULL NULL,
    PES_PRINCIPAIS_FORNECEDORES   	VARCHAR(255) DEFAULT '' NULL,
    PES_PRINCIPAIS_CLIENTES       	VARCHAR(255) DEFAULT '' NULL,
    PES_EXPORTACAO                	INTEGER DEFAULT 0 NULL,
	PES_CRED_SUJ_APROVACAO          INTEGER DEFAULT 0 NULL,
    PRIMARY KEY(PES_ID)
)
GO
CREATE TABLE PTC_PROGRAMA_MODULO_PGM ( 
    PGM_ID    	INTEGER NOT NULL,
    PGM_PRO_ID	INTEGER NOT NULL,
    PGM_MOD_ID	INTEGER NOT NULL,
    PRIMARY KEY(PGM_ID)
)
GO
CREATE TABLE PTC_PROGRAMA_PRO ( 
    PRO_ID             	INTEGER NOT NULL,
    PRO_DESCRICAO_CURTA	VARCHAR(20) NOT NULL,
    PRO_DESCRICAO      	VARCHAR(60) NOT NULL,
    PRO_COD_PTC        	VARCHAR(10) NOT NULL,
    PRIMARY KEY(PRO_ID)
)
GO
CREATE TABLE PTC_TELAS_PROGRAMA_TLP ( 
    TLP_ID          	INTEGER NOT NULL,
    TLP_PRO_ID      	INTEGER DEFAULT NULL NULL,
    TLP_NOME_ARQUIVO	VARCHAR(100) DEFAULT NULL NULL,
    PRIMARY KEY(TLP_ID)
)


CREATE TABLE PTC_TIPO_PESSOA_TPS ( 
    TPS_ID        	INTEGER NOT NULL,
    TPS_CODIGO_ERP	VARCHAR(25) DEFAULT NULL NULL,
    TPS_TIPO      	VARCHAR(250) DEFAULT NULL NULL,
    TPS_SEQUENCIA 	INTEGER NULL,
    PRIMARY KEY(TPS_ID)
)

GO

GO
CREATE TABLE PTC_USUARIO_USU ( 
    USU_ID                        	INTEGER NOT NULL,
    USU_NOME                      	VARCHAR(60) NOT NULL,
    USU_USUARIO                   	VARCHAR(20) NOT NULL,
    USU_SENHA                     	VARCHAR(250) NULL,
    USU_ULTIMO_LOGIN              	VARCHAR(250) NULL,
    USU_RAMAL                     	VARCHAR(10) DEFAULT NULL NULL,
    USU_USUARIO_ERP               	VARCHAR(50) NULL,
    USU_REPRESENTANTE_ERP         	VARCHAR(15) DEFAULT NULL NULL,
    USU_EMAIL                     	VARCHAR(100) DEFAULT NULL NULL,
    USU_FAX                       	VARCHAR(25) DEFAULT NULL NULL,
    USU_CARTEIRA                  	VARCHAR(20) DEFAULT NULL NULL,
    USU_MODIFICA_PEDIDO_ERP       	INTEGER DEFAULT NULL NULL,
    USU_CADASTRA_PEDIDO_OUTROS    	INTEGER DEFAULT NULL NULL,
    USU_TELEFONE                  	VARCHAR(25) DEFAULT NULL NULL,
    USU_IMAGEM                    	VARCHAR(250) NULL,
    USU_EMAIL_SECUNDARIO          	VARCHAR(100) DEFAULT NULL NULL,
    USU_MODIFICA_CLIENTE_ERP      	INTEGER DEFAULT NULL NULL,
    USU_LIBERA_PEDIDO_FECHADO     	INTEGER DEFAULT 0 NOT NULL,
    USU_VISUALIZA_CLI_SEM_CANAL   	INTEGER DEFAULT 0 NULL,
    USU_VISUALIZA_HIST_CREDITO    	INTEGER DEFAULT 0 NULL,
    USU_INTERNO                   	INTEGER DEFAULT 1 NULL,
    USU_CAD_DIAS_MEDIA_COND_PTGO  	INTEGER DEFAULT 0 NULL,
    USU_LIBERA_MODIFICACAO_USUARIO	INTEGER DEFAULT 0 NULL,
    USU_LIBERA_MODIFICACAO_REPRES 	INTEGER DEFAULT 0 NULL,
    USU_RECEBE_EMAIL_ENVIADO      	INTEGER DEFAULT 0 NULL,
    USU_RECEBE_EMAIL_APROV_REPROV 	VARCHAR(2) DEFAULT '' NULL,
    USU_RESPONDE_SAC              	INTEGER DEFAULT 0 NULL,
    USU_REC_EMAIL_APROV_REPROV_CLI	VARCHAR(5) DEFAULT '' NULL,
    USU_COR_MENU                  	VARCHAR(30) NULL,
    USU_COR_TEXTO_MENU            	VARCHAR(30) NULL,
    PRIMARY KEY(USU_ID)
)

GO



 









